server:
  port: 8081

spring:
  application:
    name: upload-client

grpc:
  server:
    port: -1
  client:
    upload-service:
      address: static://localhost:9090
      negotiation-type: plaintext
