syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.saebak.upload";

package upload;

service FileUploadService {
  rpc UploadFile (stream UploadRequest) returns (UploadResponse);
  rpc DownloadFile (DownloadRequest) returns (stream FileChunk);
  rpc ListFiles (ListFilesRequest) returns (ListFilesResponse);
}

message UploadRequest {
  oneof payload {
    FileInfo info = 1;
    bytes chunk = 2;
  }
}

message FileInfo {
  string filename = 1;
}

message UploadResponse {
  bool success = 1;
  string message = 2;
  int64 size = 3;
}

message DownloadRequest {
  string filename = 1;
}

message FileChunk {
  bytes chunk = 1;
}

message ListFilesRequest {
}

message ListFilesResponse {
  repeated FileEntry files = 1;
}

message FileEntry {
  string filename = 1;
  int64 size = 2;
}
